/***
This file is autogenerated, please do not edit it.
To generate an updated version, please run `yarn genreg`

If you register your helper with this index, it can be referenced more easily.

e.g. without registering

  import fetcher from '@helpers/fetcher
  import poster from '@helpers/poster

e.g. with registering

  import { fetcher, poster } from '@helpers/index'
*/

export { default as simpleArray } from './simple-array';
